platform :ios, '12.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'AdvancedMap.Objective-C' do
  # CartoMobileSDK is linked manually from local build
  pod 'Toast', '~> 3.0'

  target 'AdvancedMap.Objective-C.UITests' do
    inherit! :search_paths
  end

end
